### ISSUE TITLE
NoSuchMethodError: 'seoOpenGraphJS'

### ISSUE THREAD

**Issue by GanderwaD** [Eng-Mouaz-M-AlShahmeh/meta_seo_with_go_router_example#1]
Constantly getting NoSuchMethodError: 'seoOpenGraphJS' error at the start of application

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Give me the screen shot of code and the error

**Comment by GanderwaD** [comment]
![dummy](https://user-images.githubusercontent.com/106515158/227206204-5e0f417a-85d1-44f9-af05-dbadfe4d5a70.png)
this is a screenshot from go router example

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
refer th [meta_seo package](https://pub.dev/packages/meta_seo) readme for config the functions before.

**Comment by GanderwaD** [comment]
this is your example application and I get the same error on my application

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
let me see the main.dart code

**Comment by GanderwaD** [comment]
https://github.com/Eng-Mouaz-M-AlShahmeh/meta_seo_with_go_router_example/blob/main/lib/main.dart

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
It is running well on the latest version of meta_seo 3.0.5

**Comment by GanderwaD** [comment]
what branch are u on maybe u didn't publish to main ?

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
There is one branch "main"

**Comment by GanderwaD** [comment]
I just downloaded zip from this repo, did pub get and press start and this is the error

**Comment by Eng-Mouaz-M-AlShahmeh** [comment]
Make screenshot of main.dart on your side
